# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f252cb82e30d53a0fd155980249ebc29"
application_url = "https://runn-search-ai-indexer-1029558196901.europe-north2.run.app"
embedded = true
name = "Runn Search AI Indexer"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://runn-search-ai-indexer-1029558196901.europe-north2.run.app/auth/callback"
]

[build]
automatically_update_urls_on_dev = false
